#!/bin/bash

# Date: 07/10/2021
# Author: Israel Pereira Tavares da Silva
# This is the main entry point of the program. In a nut shell it
# call either nn or fl scripts to either write a new note or to 
# read existing notes from the data dir.

case $1 in
	""    ) source scripts/nn ;;
	"new" ) source scripts/nn ;;
	"read") source scripts/fl ;;
	*     )	source scripts/help ; exit 1 ;;
esac

