#!/bin/bash

# Date: 07/10/2021
# Author: Israel Pereira Tavares da Silva
# This is the main entry point of the program. In a nutshell it
# call either nn or fl scripts to either write a new note or to 
# read existing notes from the data dir.

case $1 in
	""       ) source scripts/new.sh ;;
	"new"    ) source scripts/new.sh ;;
	"read"   ) source scripts/read.sh ;;
	"shuffle") source scripts/shuffle.sh ;;
	*        ) source scripts/help.sh ; exit 1 ;;
esac

