#!/bin/bash

file=$1

a="/^\[ANSWER\]/,/^\[ANSWER\]$/ { /^\[ANSWER\]$/d; /^\[ANSWER\]$/d; p; }"
answer=`sed -n "$a" $file`

read -p "> " reply

case "$reply" in
	"$answer") printf "\n  Correct \u2714\n\n" ; exit 1 ;;
	"hint"	 ) ./scripts/hint $file ;;
	"answer" ) printf "\n%s\n\n" $answer ;;
	*				 ) printf "\n  Wrong \u274c\n\n" ; source $0 ;;
esac 

source $0
